# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

steps:
- task: AzurePowerShell@5
  inputs:
    ScriptType: 'InlineScript'
    Inline: |
      $url = "$(Build.Repository.Uri)".Replace("https://", "")
      $url = "https://$env:SYSTEM_ACCESSTOKEN@$url"
      # Install Azure Blueprint PS Module
      Install-Module -Name Az.Blueprint -Verbose -Scope CurrentUser; Update-Help -Force -ErrorAction SilentlyContinuescripts 
      
      $b = Get-AzBlueprint -Name 'CAF_Workshop_Landing_Zone_Demo' -SubscriptionId '8b2ef784-0c0d-424c-8a7a-aa1304a0366a' -Version 'v4.8'
      
      Import-AzBlueprintWithArtifact -Name 'CAF_Workshop_Landing_Zone_Demo' -SubscriptionId '8b2ef784-0c0d-424c-8a7a-aa1304a0366a' -InputPath  '.\blueprints\CAF_Workshop_Landing_Zone_Demo'
    FailOnStandardError: true
    azurePowerShellVersion: 'LatestVersion'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
